.TH goldielocs 1 "December 9, 2010" "Version 0.1" "USER COMMANDS"
.SH NAME
goldielocs
.SH SYNPOSIS
goldielocs command [command args]

.SH DESCRIPTION
Description placeholder here...

.SH COMMANDS

.SS 
list
lists all known locations and aliases

.SS 
placeholder
placeholder command entry here...

.SH HISTORY
.TP
2009 Original implementation written in rc by Canaan
.TP
2010 Ported to bash 
